services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5135
      - ASPNETCORE_HTTPS_PORTS=7013
      - ASPNETCORE_URLS=http://0.0.0.0:5135
      - ASPNETCORE_URLS=https://0.0.0.0:7013
    ports:
      - "7013:7013"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "-v", "-k", "https://localhost:7013/api/health"]  # -k is for insecure SSL !LOCAL ONLY!
      interval: 30s
      timeout: 10s
      retries: 3
